version: '3'

services:
    web:
        build: .
        container_name: belajar_django_blog

        command: guincorn myproject.wsgi:application --bind 0.0.0.0:9005



        volumes :
          - .:/app
        ports:
          - "9005:9005"